[package]
name = "notes_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

egui = {version = "0.21.0", features = ["persistence"]}
eframe = "0.21.0"
open = "4.0.1"
glob = "0.3.0"

